name: Whitelist
main: com.bitzcraftonline.whitelist.Whitelist
version: 1.1.1.0000a
depend: [Vault]
commands:
  whitelist help:
      description: Base command for whitelist.
permissions:
  whitelist.*:
    description: Gives the user permission for all whitelist commands
    children:
      whitelist.admin: true
      whitelist.add: true
      whitelist.remove: true